author: kuzqi
name: System
main: dev.me.kuzqi.core.staffsystem.Main
version: 1.0
commands:
  help:
  discord:
  dis:
  store:
  youtube:
  yt:
  namemc:
  fly:
  gmc:
  gms:
  atp:
  rename:
  v:
  vlist:
  vtp:
  invsee:
  lockchat:
  lc:
  addrank:
  setrank:
  temprank:
  heal:
  clearchat:
  cc:
  broadcast:
  bc:
  sr:
  systemreload:
  server:
  hub:
  send: