###################################################################
# +-------------------------------------------------------------+ #
# |             ___ __   __ ___  _____  ___  __  __             | #
# |            / __|\ \ / // __||_   _|| __||  \/  |   		    | #
# |            \__ \ \ V / \__ \  | |  | _| | |\/| |    	    | #
# |            |___/  |_|  |___/  |_|  |___||_|  |_|            | #
# |                                             		        | #
# |             Plugin Developed by @kuzqi 1.0-BETA             | #
# +-------------------------------------------------------------+ #
###################################################################

servers:
 lobby-server: lobby # for /hub
 allowed-servers:
  - creative
  - pvp
  - skypvp
  - redpvp
  - duels
  - lobby


tab:
 header: "&bSpirits&3MC"
 footer: "&7store.spiritsmc.net"

health-bar:
 format: "&c$player-health ❤"

ranks: # for /setrank, /temprank, /addrank
 allowed:
  - mod
  - miniyt
  - youtuber
  - spirits
  - elite
  - epic
  - vip
  - member
 exempt-players:
  - kuzqi

blocked-words:
 - ".com"
 - ".net"
 - ".xyz"
 - ".club"
 - ".gg"
 - "play."
 - "mc."
 - "https://"
 - "http://"

blocked-commands:
  message: "&cCommand not found. Type /help for help"
  commands:
   - "plugins"
   - "pl"
   - "bukkit:pl"
   - "bukkit:plugins"
   - "?"
   - "bukkit:?"
   - "ver"
   - "version"
   - "bukkit:ver"
   - "bukkit:version"

clear-lag:
 enable: false
 warn-message-task-timer: 120 # in seconds
 warn-message: "&cAll ground items will be cleared in 100 seconds!"
 clear-items-message-task-timer: 240 # in seconds
 clear-items: "&cAll ground items has been cleared!"